// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spike/v1/greeter.proto

package spikev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_spike_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spike_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_spike_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_spike_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_spike_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_spike_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_spike_v1_greeter_proto protoreflect.FileDescriptor

const file_spike_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x16spike/v1/greeter.proto\x12\bspike.v1\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xfd\x01\n" +
	"\aGreeter\x128\n" +
	"\bSayHello\x12\x16.spike.v1.HelloRequest\x1a\x14.spike.v1.HelloReply\x12=\n" +
	"\vListReplies\x12\x16.spike.v1.HelloRequest\x1a\x14.spike.v1.HelloReply0\x01\x12?\n" +
	"\rCollectHellos\x12\x16.spike.v1.HelloRequest\x1a\x14.spike.v1.HelloReply(\x01\x128\n" +
	"\x04Chat\x12\x16.spike.v1.HelloRequest\x1a\x14.spike.v1.HelloReply(\x010\x01B+Z)github.com/grpcws/wsgrpc/spike/v1;spikev1b\x06proto3"

var (
	file_spike_v1_greeter_proto_rawDescOnce sync.Once
	file_spike_v1_greeter_proto_rawDescData []byte
)

func file_spike_v1_greeter_proto_rawDescGZIP() []byte {
	file_spike_v1_greeter_proto_rawDescOnce.Do(func() {
		file_spike_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spike_v1_greeter_proto_rawDesc), len(file_spike_v1_greeter_proto_rawDesc)))
	})
	return file_spike_v1_greeter_proto_rawDescData
}

var file_spike_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spike_v1_greeter_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: spike.v1.HelloRequest
	(*HelloReply)(nil),   // 1: spike.v1.HelloReply
}
var file_spike_v1_greeter_proto_depIdxs = []int32{
	0, // 0: spike.v1.Greeter.SayHello:input_type -> spike.v1.HelloRequest
	0, // 1: spike.v1.Greeter.ListReplies:input_type -> spike.v1.HelloRequest
	0, // 2: spike.v1.Greeter.CollectHellos:input_type -> spike.v1.HelloRequest
	0, // 3: spike.v1.Greeter.Chat:input_type -> spike.v1.HelloRequest
	1, // 4: spike.v1.Greeter.SayHello:output_type -> spike.v1.HelloReply
	1, // 5: spike.v1.Greeter.ListReplies:output_type -> spike.v1.HelloReply
	1, // 6: spike.v1.Greeter.CollectHellos:output_type -> spike.v1.HelloReply
	1, // 7: spike.v1.Greeter.Chat:output_type -> spike.v1.HelloReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spike_v1_greeter_proto_init() }
func file_spike_v1_greeter_proto_init() {
	if File_spike_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spike_v1_greeter_proto_rawDesc), len(file_spike_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spike_v1_greeter_proto_goTypes,
		DependencyIndexes: file_spike_v1_greeter_proto_depIdxs,
		MessageInfos:      file_spike_v1_greeter_proto_msgTypes,
	}.Build()
	File_spike_v1_greeter_proto = out.File
	file_spike_v1_greeter_proto_goTypes = nil
	file_spike_v1_greeter_proto_depIdxs = nil
}
