// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpcws/frame/v1/frame.proto

package framev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload for a BEGIN frame. Sent by the client to open a stream.
type BeginPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full gRPC method path: "/package.ServiceName/MethodName"
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Request metadata (equivalent to gRPC request headers).
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginPayload) Reset() {
	*x = BeginPayload{}
	mi := &file_grpcws_frame_v1_frame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginPayload) ProtoMessage() {}

func (x *BeginPayload) ProtoReflect() protoreflect.Message {
	mi := &file_grpcws_frame_v1_frame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginPayload.ProtoReflect.Descriptor instead.
func (*BeginPayload) Descriptor() ([]byte, []int) {
	return file_grpcws_frame_v1_frame_proto_rawDescGZIP(), []int{0}
}

func (x *BeginPayload) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BeginPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Payload for a HEADER frame. Sent by the server before the first MSG.
type HeaderPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server initial metadata (response headers).
	Headers       map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderPayload) Reset() {
	*x = HeaderPayload{}
	mi := &file_grpcws_frame_v1_frame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderPayload) ProtoMessage() {}

func (x *HeaderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_grpcws_frame_v1_frame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderPayload.ProtoReflect.Descriptor instead.
func (*HeaderPayload) Descriptor() ([]byte, []int) {
	return file_grpcws_frame_v1_frame_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderPayload) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Payload for an END or RESET frame.
type EndPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC status code. 0 = OK.
	StatusCode uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Human-readable status message. Empty on success.
	StatusMessage string `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	// Trailing metadata from the server handler.
	Trailers      map[string]string `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndPayload) Reset() {
	*x = EndPayload{}
	mi := &file_grpcws_frame_v1_frame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndPayload) ProtoMessage() {}

func (x *EndPayload) ProtoReflect() protoreflect.Message {
	mi := &file_grpcws_frame_v1_frame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndPayload.ProtoReflect.Descriptor instead.
func (*EndPayload) Descriptor() ([]byte, []int) {
	return file_grpcws_frame_v1_frame_proto_rawDescGZIP(), []int{2}
}

func (x *EndPayload) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EndPayload) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *EndPayload) GetTrailers() map[string]string {
	if x != nil {
		return x.Trailers
	}
	return nil
}

var File_grpcws_frame_v1_frame_proto protoreflect.FileDescriptor

const file_grpcws_frame_v1_frame_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpcws/frame/v1/frame.proto\x12\x0fgrpcws.frame.v1\"\xac\x01\n" +
	"\fBeginPayload\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12G\n" +
	"\bmetadata\x18\x02 \x03(\v2+.grpcws.frame.v1.BeginPayload.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\rHeaderPayload\x12E\n" +
	"\aheaders\x18\x01 \x03(\v2+.grpcws.frame.v1.HeaderPayload.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\n" +
	"EndPayload\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12E\n" +
	"\btrailers\x18\x03 \x03(\v2).grpcws.frame.v1.EndPayload.TrailersEntryR\btrailers\x1a;\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B0Z.github.com/fugue-rpc/fugue-go/frame/v1;framev1b\x06proto3"

var (
	file_grpcws_frame_v1_frame_proto_rawDescOnce sync.Once
	file_grpcws_frame_v1_frame_proto_rawDescData []byte
)

func file_grpcws_frame_v1_frame_proto_rawDescGZIP() []byte {
	file_grpcws_frame_v1_frame_proto_rawDescOnce.Do(func() {
		file_grpcws_frame_v1_frame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcws_frame_v1_frame_proto_rawDesc), len(file_grpcws_frame_v1_frame_proto_rawDesc)))
	})
	return file_grpcws_frame_v1_frame_proto_rawDescData
}

var file_grpcws_frame_v1_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpcws_frame_v1_frame_proto_goTypes = []any{
	(*BeginPayload)(nil),  // 0: grpcws.frame.v1.BeginPayload
	(*HeaderPayload)(nil), // 1: grpcws.frame.v1.HeaderPayload
	(*EndPayload)(nil),    // 2: grpcws.frame.v1.EndPayload
	nil,                   // 3: grpcws.frame.v1.BeginPayload.MetadataEntry
	nil,                   // 4: grpcws.frame.v1.HeaderPayload.HeadersEntry
	nil,                   // 5: grpcws.frame.v1.EndPayload.TrailersEntry
}
var file_grpcws_frame_v1_frame_proto_depIdxs = []int32{
	3, // 0: grpcws.frame.v1.BeginPayload.metadata:type_name -> grpcws.frame.v1.BeginPayload.MetadataEntry
	4, // 1: grpcws.frame.v1.HeaderPayload.headers:type_name -> grpcws.frame.v1.HeaderPayload.HeadersEntry
	5, // 2: grpcws.frame.v1.EndPayload.trailers:type_name -> grpcws.frame.v1.EndPayload.TrailersEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpcws_frame_v1_frame_proto_init() }
func file_grpcws_frame_v1_frame_proto_init() {
	if File_grpcws_frame_v1_frame_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcws_frame_v1_frame_proto_rawDesc), len(file_grpcws_frame_v1_frame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcws_frame_v1_frame_proto_goTypes,
		DependencyIndexes: file_grpcws_frame_v1_frame_proto_depIdxs,
		MessageInfos:      file_grpcws_frame_v1_frame_proto_msgTypes,
	}.Build()
	File_grpcws_frame_v1_frame_proto = out.File
	file_grpcws_frame_v1_frame_proto_goTypes = nil
	file_grpcws_frame_v1_frame_proto_depIdxs = nil
}
