// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: echo/v1/echo.proto

package echov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_echo_v1_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_echo_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StreamNReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNReq) Reset() {
	*x = StreamNReq{}
	mi := &file_echo_v1_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNReq) ProtoMessage() {}

func (x *StreamNReq) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v1_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNReq.ProtoReflect.Descriptor instead.
func (*StreamNReq) Descriptor() ([]byte, []int) {
	return file_echo_v1_echo_proto_rawDescGZIP(), []int{1}
}

func (x *StreamNReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StreamNReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_echo_v1_echo_proto protoreflect.FileDescriptor

const file_echo_v1_echo_proto_rawDesc = "" +
	"\n" +
	"\x12echo/v1/echo.proto\x12\aecho.v1\"\x1b\n" +
	"\x03Msg\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"8\n" +
	"\n" +
	"StreamNReq\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xe3\x01\n" +
	"\x04Echo\x12\"\n" +
	"\x04Echo\x12\f.echo.v1.Msg\x1a\f.echo.v1.Msg\x12*\n" +
	"\n" +
	"EchoStream\x12\f.echo.v1.Msg\x1a\f.echo.v1.Msg0\x01\x12+\n" +
	"\vEchoCollect\x12\f.echo.v1.Msg\x1a\f.echo.v1.Msg(\x01\x12*\n" +
	"\bEchoBidi\x12\f.echo.v1.Msg\x1a\f.echo.v1.Msg(\x010\x01\x122\n" +
	"\vEchoStreamN\x12\x13.echo.v1.StreamNReq\x1a\f.echo.v1.Msg0\x01B+Z)github.com/fugue-rpc/fugue/echo/v1;echov1b\x06proto3"

var (
	file_echo_v1_echo_proto_rawDescOnce sync.Once
	file_echo_v1_echo_proto_rawDescData []byte
)

func file_echo_v1_echo_proto_rawDescGZIP() []byte {
	file_echo_v1_echo_proto_rawDescOnce.Do(func() {
		file_echo_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_v1_echo_proto_rawDesc), len(file_echo_v1_echo_proto_rawDesc)))
	})
	return file_echo_v1_echo_proto_rawDescData
}

var file_echo_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_v1_echo_proto_goTypes = []any{
	(*Msg)(nil),        // 0: echo.v1.Msg
	(*StreamNReq)(nil), // 1: echo.v1.StreamNReq
}
var file_echo_v1_echo_proto_depIdxs = []int32{
	0, // 0: echo.v1.Echo.Echo:input_type -> echo.v1.Msg
	0, // 1: echo.v1.Echo.EchoStream:input_type -> echo.v1.Msg
	0, // 2: echo.v1.Echo.EchoCollect:input_type -> echo.v1.Msg
	0, // 3: echo.v1.Echo.EchoBidi:input_type -> echo.v1.Msg
	1, // 4: echo.v1.Echo.EchoStreamN:input_type -> echo.v1.StreamNReq
	0, // 5: echo.v1.Echo.Echo:output_type -> echo.v1.Msg
	0, // 6: echo.v1.Echo.EchoStream:output_type -> echo.v1.Msg
	0, // 7: echo.v1.Echo.EchoCollect:output_type -> echo.v1.Msg
	0, // 8: echo.v1.Echo.EchoBidi:output_type -> echo.v1.Msg
	0, // 9: echo.v1.Echo.EchoStreamN:output_type -> echo.v1.Msg
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_v1_echo_proto_init() }
func file_echo_v1_echo_proto_init() {
	if File_echo_v1_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_v1_echo_proto_rawDesc), len(file_echo_v1_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_v1_echo_proto_goTypes,
		DependencyIndexes: file_echo_v1_echo_proto_depIdxs,
		MessageInfos:      file_echo_v1_echo_proto_msgTypes,
	}.Build()
	File_echo_v1_echo_proto = out.File
	file_echo_v1_echo_proto_goTypes = nil
	file_echo_v1_echo_proto_depIdxs = nil
}
