// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: echo/v1/echo.proto

package echov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Echo_Echo_FullMethodName        = "/echo.v1.Echo/Echo"
	Echo_EchoStream_FullMethodName  = "/echo.v1.Echo/EchoStream"
	Echo_EchoCollect_FullMethodName = "/echo.v1.Echo/EchoCollect"
	Echo_EchoBidi_FullMethodName    = "/echo.v1.Echo/EchoBidi"
	Echo_EchoStreamN_FullMethodName = "/echo.v1.Echo/EchoStreamN"
)

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	// Unary: send one message, receive one message.
	Echo(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error)
	// Server-streaming: send one message, receive N messages.
	EchoStream(ctx context.Context, in *Msg, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Msg], error)
	// Client-streaming: send N messages, receive one message (concatenated).
	EchoCollect(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Msg, Msg], error)
	// Bidi-streaming: each sent message is echoed back immediately.
	EchoBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Msg, Msg], error)
	// Server-streaming N: configurable response count for benchmarking.
	EchoStreamN(ctx context.Context, in *StreamNReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Msg], error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Echo(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Msg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg)
	err := c.cc.Invoke(ctx, Echo_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoStream(ctx context.Context, in *Msg, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Msg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], Echo_EchoStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Msg, Msg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoStreamClient = grpc.ServerStreamingClient[Msg]

func (c *echoClient) EchoCollect(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Msg, Msg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[1], Echo_EchoCollect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Msg, Msg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoCollectClient = grpc.ClientStreamingClient[Msg, Msg]

func (c *echoClient) EchoBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Msg, Msg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[2], Echo_EchoBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Msg, Msg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoBidiClient = grpc.BidiStreamingClient[Msg, Msg]

func (c *echoClient) EchoStreamN(ctx context.Context, in *StreamNReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Msg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[3], Echo_EchoStreamN_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNReq, Msg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoStreamNClient = grpc.ServerStreamingClient[Msg]

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility.
type EchoServer interface {
	// Unary: send one message, receive one message.
	Echo(context.Context, *Msg) (*Msg, error)
	// Server-streaming: send one message, receive N messages.
	EchoStream(*Msg, grpc.ServerStreamingServer[Msg]) error
	// Client-streaming: send N messages, receive one message (concatenated).
	EchoCollect(grpc.ClientStreamingServer[Msg, Msg]) error
	// Bidi-streaming: each sent message is echoed back immediately.
	EchoBidi(grpc.BidiStreamingServer[Msg, Msg]) error
	// Server-streaming N: configurable response count for benchmarking.
	EchoStreamN(*StreamNReq, grpc.ServerStreamingServer[Msg]) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoServer struct{}

func (UnimplementedEchoServer) Echo(context.Context, *Msg) (*Msg, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoServer) EchoStream(*Msg, grpc.ServerStreamingServer[Msg]) error {
	return status.Error(codes.Unimplemented, "method EchoStream not implemented")
}
func (UnimplementedEchoServer) EchoCollect(grpc.ClientStreamingServer[Msg, Msg]) error {
	return status.Error(codes.Unimplemented, "method EchoCollect not implemented")
}
func (UnimplementedEchoServer) EchoBidi(grpc.BidiStreamingServer[Msg, Msg]) error {
	return status.Error(codes.Unimplemented, "method EchoBidi not implemented")
}
func (UnimplementedEchoServer) EchoStreamN(*StreamNReq, grpc.ServerStreamingServer[Msg]) error {
	return status.Error(codes.Unimplemented, "method EchoStreamN not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}
func (UnimplementedEchoServer) testEmbeddedByValue()              {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	// If the following call panics, it indicates UnimplementedEchoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Msg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).EchoStream(m, &grpc.GenericServerStream[Msg, Msg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoStreamServer = grpc.ServerStreamingServer[Msg]

func _Echo_EchoCollect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).EchoCollect(&grpc.GenericServerStream[Msg, Msg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoCollectServer = grpc.ClientStreamingServer[Msg, Msg]

func _Echo_EchoBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).EchoBidi(&grpc.GenericServerStream[Msg, Msg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoBidiServer = grpc.BidiStreamingServer[Msg, Msg]

func _Echo_EchoStreamN_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).EchoStreamN(m, &grpc.GenericServerStream[StreamNReq, Msg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_EchoStreamNServer = grpc.ServerStreamingServer[Msg]

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.v1.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EchoStream",
			Handler:       _Echo_EchoStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EchoCollect",
			Handler:       _Echo_EchoCollect_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EchoBidi",
			Handler:       _Echo_EchoBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "EchoStreamN",
			Handler:       _Echo_EchoStreamN_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "echo/v1/echo.proto",
}
